name: "Deploy via SSH"
description: "Copy docker-compose file and deploy using docker compose over SSH"

inputs:
  compose-file:
    required: true
    description: "Path to the docker-compose file to deploy (e.g., docker-compose-prod.yml)"

runs:
  using: "composite"
  steps:
    - name: Copy docker-compose file to remote
      uses: appleboy/scp-action@v1
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        source: ${{ inputs.compose-file }}
        target: "~/zrvr/"

    - name: Deploy application via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ env.SSH_HOST }}
        username: ${{ env.SSH_USER }}
        key: ${{ env.SSH_KEY }}
        script: |
          cd ~/zrvr
          docker compose pull
          docker compose down || true
          docker compose up -d
