name: Deploy Template

on:
  workflow_call:
    inputs:
      compose-file:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy docker-compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ inputs.compose-file }}
          target: "~/zrvr/docker-compose.yml"
      - name: Deploy application via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/zrvr
            docker compose pull
            docker compose down || true
            docker compose up -d
