name: Deploy Template

on:
  workflow_call:
    inputs:
      ssh-host:
        required: true
        type: string
      ssh-user:
        required: true
        type: string
      ssh-key:
        required: true
        type: string
      compose-file:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy docker-compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ inputs.ssh-host }}
          username: ${{ inputs.ssh-user }}
          key: ${{ inputs.ssh-key }}
          source: ${{ inputs.compose-file }}
          target: "~/docker-compose.yml"
      - name: Deploy application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.ssh-host }}
          username: ${{ inputs.ssh-user }}
          key: ${{ inputs.ssh-key }}
          script: |
            docker compose pull
            docker compose down || true
            docker compose up -d
