name: Deploy Template

on:
  workflow_call:
    inputs:
      env-file:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Replace env vars
        run: bash scripts/replace-env-vars.sh "$INPUT_ENV-FILE"
      - name: Deploy application
        run: ./deploy.sh